[project]
name = "pyeventbt"
version = "0.0.13"
description = "Event-driven backtesting and live trading framework for Python and MetaTrader 5"
authors = [
    { name = "Marti Castany" },
    { name = "Alain Porto" },
]
readme = "README.md"
license = "Apache-2.0"
keywords = [
    "mt5",
    "metatrader5",
    "backtesting",
    "mt5 python",
    "event-driven",
    "trading",
    "algorithmic-trading",
    "python-trading",
    "quantitative-finance",
    "live-trading",
    "metatrader",
    "forex",
    "technical-analysis",
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Intended Audience :: Financial and Insurance Industry",
    "Programming Language :: Python :: 3.12",
    "Topic :: Office/Business :: Financial :: Investment",
    "Topic :: Scientific/Engineering :: Information Analysis",
]
requires-python = ">=3.12,<3.13"
dependencies = [
    "python-dotenv>=1.1.1,<2.0.0",
    "pydantic>=2.12.3,<3.0.0",
    "numpy>=2.0.0,<3.0.0",
    "polars>=1.35.0,<2.0.0",
    "pandas>=2.2.3,<3.0.0",
    "numba>=0.62.1,<1.0.0",
    "matplotlib>=3.7.0,<4.0.0",
    "scipy>=1.10.0,<2.0.0",
    "scikit-learn>=1.3.0,<2.0.0",
    "PyYAML>=6.0,<7.0",
    "quantdle>=1.0.0,<2.0.0",
    "plotly (>=7.1.0,<8.0.0)",
]

[project.urls]
Homepage = "https://pyeventbt.com"
Repository = "https://github.com/marticastany/pyeventbt"
Documentation = "https://pyeventbt.com"

[project.scripts]
pyeventbt = "pyeventbt.app:main"

[tool.poetry]
packages = [{ include = "pyeventbt" }]

[build-system]
requires = ["poetry-core>=2.0"]
build-backend = "poetry.core.masonry.api"
